Outputs:
  AccessKeycipermauser1:
    Description: 'Access Key of user: cipermauser1 in group traviscipermagroup'
    Value:
      Ref: userkeycipermauser1
  AccessKeycipermauser2:
    Description: 'Access Key of user: cipermauser2 in group traviscipermagroup'
    Value:
      Ref: userkeycipermauser2
  Passwordcipermauser1:
    Description: Default password of new user cipermauser1 in group traviscipermagroup
    Value: e3359c8b7070a4ec
  Passwordcipermauser2:
    Description: Default password of new user cipermauser2 in group traviscipermagroup
    Value: 0f5d67b66992eee0
  SecretAccessKeycipermauser1:
    Description: 'Secret Key of new user: cipermauser1 in group traviscipermagroup'
    Value:
      Fn::GetAtt:
      - userkeycipermauser1
      - SecretAccessKey
  SecretAccessKeycipermauser2:
    Description: 'Secret Key of new user: cipermauser2 in group traviscipermagroup'
    Value:
      Fn::GetAtt:
      - userkeycipermauser2
      - SecretAccessKey
Resources:
  DeleteCustomResourcetraviscipermagroup:
    DependsOn: PipelineBuckettraviscipermagroup
    Properties:
      BucketName: traviscipermagroup
      ServiceToken:
        Fn::GetAtt:
        - S3DelObjectFunction
        - Arn
    Type: AWS::CloudFormation::CustomResource
  LambdaBaseRole:
    Properties:
      Description:
        Fn::Join:
        - ' '
        - - Base Policy for all lambda function roles in
          - Ref: AWS::StackName
      PolicyDocument:
        Statement:
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Effect: Allow
          Resource: arn:aws:logs:*:*:*
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy
  PipelineBuckettraviscipermagroup:
    Properties:
      AccessControl: Private
      BucketName: traviscipermagroup
    Type: AWS::S3::Bucket
  S3DelObjectFunction:
    Properties:
      CodeUri: s3://ctnsampackages/9573dfa48b707206b87f84fe017bdf57
      Description: Deletes Objects from S3
      Environment:
        Variables:
          EXECUTION_TIMEOUT: '172800'
          IAM_ROLE: iam role with ssm and s3 access
          INDIR: inputs
          LOGDIR: logs
          LOGFILE: lambda_log.txt
          MONITOR: true
          OUTDIR: results
          REGION: us-east-1
          SECURITY_GROUPS: Type of instance to launch.
      Handler: helper.handler_deldir
      Role:
        Fn::GetAtt:
        - S3MakePathRole
        - Arn
      Runtime: python3.6
      Timeout: 30
    Type: AWS::Serverless::Function
  S3MakePathRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - Ref: LambdaBaseRole
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - s3:DeleteObject
            - s3:ListBucket
            - s3:PutObject
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: write_s3_policy
    Type: AWS::IAM::Role
  S3PutObjectFunction:
    Properties:
      CodeUri: s3://ctnsampackages/27ea3ea5b3139f04f4913b971547bb29
      Description: Puts Objects in S3
      Environment:
        Variables:
          EXECUTION_TIMEOUT: '172800'
          IAM_ROLE: iam role with ssm and s3 access
          INDIR: inputs
          LOGDIR: logs
          LOGFILE: lambda_log.txt
          MONITOR: true
          OUTDIR: results
          REGION: us-east-1
          SECURITY_GROUPS: Type of instance to launch.
      Handler: helper.handler_mkdir
      Role:
        Fn::GetAtt:
        - S3MakePathRole
        - Arn
      Runtime: python3.6
      Timeout: 30
    Type: AWS::Serverless::Function
  traviscipermagroupusercipermauser1:
    Properties:
      LoginProfile:
        Password: e3359c8b7070a4ec
        PasswordResetRequired: 'false'
      Path: /traviscipermagroup/
      UserName: cipermauser1us-east-1
    Type: AWS::IAM::User
  traviscipermagroupusercipermauser2:
    Properties:
      LoginProfile:
        Password: 0f5d67b66992eee0
        PasswordResetRequired: 'false'
      Path: /traviscipermagroup/
      UserName: cipermauser2us-east-1
    Type: AWS::IAM::User
  userkeycipermauser1:
    Properties:
      UserName:
        Ref: traviscipermagroupusercipermauser1
    Type: AWS::IAM::AccessKey
  userkeycipermauser2:
    Properties:
      UserName:
        Ref: traviscipermagroupusercipermauser2
    Type: AWS::IAM::AccessKey
Transform: AWS::Serverless-2016-10-31
