Outputs:
  AccessKey3050ferralhogs:
    Description: 'Access Key of user: 3050ferralhogs in group bendeskylab'
    Value:
      Ref: userkey3050ferralhogs
  AccessKeyaln2128:
    Description: 'Access Key of user: aln2128 in group bendeskylab'
    Value:
      Ref: userkeyaln2128
  Password3050ferralhogs:
    Description: Default password of new user 3050ferralhogs in group bendeskylab
    Value: 9b77193ca6c302be
  Passwordaln2128:
    Description: Default password of new user aln2128 in group bendeskylab
    Value: cc38019ae570fc07
  SecretAccessKey3050ferralhogs:
    Description: 'Secret Key of new user: 3050ferralhogs in group bendeskylab'
    Value:
      Fn::GetAtt:
      - userkey3050ferralhogs
      - SecretAccessKey
  SecretAccessKeyaln2128:
    Description: 'Secret Key of new user: aln2128 in group bendeskylab'
    Value:
      Fn::GetAtt:
      - userkeyaln2128
      - SecretAccessKey
Resources:
  BaseFolderbendeskylab:
    DependsOn: PipelineMainBucket
    Properties:
      BucketName: bendeskymonitored
      DirName: bendeskylab
      Path: ''
      ServiceToken:
        Fn::GetAtt:
        - S3PutObjectFunction
        - Arn
    Type: AWS::CloudFormation::CustomResource
  CWPermissions:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: FigLambda
      Principal: events.amazonaws.com
    Type: AWS::Lambda::Permission
  CloudWatchBusRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - events.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - Ref: CloudwatchBusPolicy
    Type: AWS::IAM::Role
  CloudwatchBusPolicy:
    Properties:
      Description:
        Fn::Join:
        - ' '
        - - Base Policy for all lambda function roles in
          - Ref: AWS::StackName
      PolicyDocument:
        Statement:
        - Action: events:*
          Effect: Allow
          Resource: '*'
          Sid: CloudWatchEventsFullAccess
        - Action: iam:PassRole
          Effect: Allow
          Resource: arn:aws:iam::*:role/AWS_Events_Invoke_Targets
          Sid: IAMPassRoleForCloudWatchEvents
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy
  DeleteCustomResource:
    DependsOn: PipelineMainBucket
    Properties:
      BucketName: bendeskymonitored
      ServiceToken:
        Fn::GetAtt:
        - S3DelObjectFunction
        - Arn
    Type: AWS::CloudFormation::CustomResource
  FigLambda:
    Properties:
      CodeUri: s3://ctnsampackages/96d3a05a74dd463addb9495c960e2bbc
      Description: Lambda Function logging start/stop for NCAP
      Events: {}
      Handler: log.eventshandler
      MemorySize: 128
      Role: arn:aws:iam::739988523141:role/lambda_dataflow
      Runtime: python3.6
      Timeout: 90
    Type: AWS::Serverless::Function
  FignameLogGroup:
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${FigLambda}
    Type: AWS::Logs::LogGroup
  InFolderbendeskylab:
    DependsOn:
    - PipelineMainBucket
    - BaseFolderbendeskylab
    Properties:
      BucketName: bendeskymonitored
      DirName: inputs
      Path: bendeskylab/
      ServiceToken:
        Fn::GetAtt:
        - S3PutObjectFunction
        - Arn
    Type: AWS::CloudFormation::CustomResource
  LambdaBaseRole:
    Properties:
      Description:
        Fn::Join:
        - ' '
        - - Base Policy for all lambda function roles in
          - Ref: AWS::StackName
      PolicyDocument:
        Statement:
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Effect: Allow
          Resource: arn:aws:logs:*:*:*
        Version: '2012-10-17'
    Type: AWS::IAM::ManagedPolicy
  LogFolderbendeskylab:
    DependsOn:
    - PipelineMainBucket
    - BaseFolderbendeskylab
    Properties:
      BucketName: bendeskymonitored
      DirName: logs
      Path: bendeskylab/
      ServiceToken:
        Fn::GetAtt:
        - S3PutObjectFunction
        - Arn
    Type: AWS::CloudFormation::CustomResource
  MainLambda:
    Properties:
      CodeUri: s3://ctnsampackages/94891b0859732900d6b1fe467f96d67e
      Description: Main Lambda Function for Serverless
      Environment:
        Variables:
          AMI: ami-01e0ff8e66e115127
          COMMAND: ls; cd ../../../../home/ubuntu; bin/run.sh "{}" "{}" "{}"
          CONFIG: config.yaml
          EXECUTION_TIMEOUT: 180
          IAM_ROLE: pmd-s3-ssm
          INDIR: inputs
          INSTANCE_TYPE: p3.2xlarge
          KEY_NAME: ta_testkey
          LAUNCH: true
          LOGDIR: logs
          LOGFILE: lambda_log.txt
          MISSING_CONFIG_ERROR: We need a config file to analyze data.
          OUTDIR: results
          REGION: us-east-1
          SECURITY_GROUPS: launch-wizard-34
          SHUTDOWN_BEHAVIOR: terminate
          SSM_TIMEOUT: 172000
          WORKING_DIRECTORY: ~/bin
          cwrolearn:
            Fn::GetAtt:
            - CloudWatchBusRole
            - Arn
          figlambarn:
            Fn::GetAtt:
            - FigLambda
            - Arn
          figlambid:
            Ref: FigLambda
      Events:
        BucketEventbendeskylab:
          Properties:
            Bucket:
              Ref: PipelineMainBucket
            Events:
            - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: bendeskylab/inputs
                - Name: suffix
                  Value: submit.json
          Type: S3
      Handler: submit_start.handler
      MemorySize: 128
      Role: arn:aws:iam::739988523141:role/lambda_dataflow
      Runtime: python3.6
      Timeout: 180
    Type: AWS::Serverless::Function
  OutFolderbendeskylab:
    DependsOn:
    - PipelineMainBucket
    - BaseFolderbendeskylab
    Properties:
      BucketName: bendeskymonitored
      DirName: results
      Path: bendeskylab/
      ServiceToken:
        Fn::GetAtt:
        - S3PutObjectFunction
        - Arn
    Type: AWS::CloudFormation::CustomResource
  PipelineMainBucket:
    Properties:
      AccessControl: Private
      BucketName: bendeskymonitored
    Type: AWS::S3::Bucket
  S3DelObjectFunction:
    Properties:
      CodeUri: s3://ctnsampackages/94891b0859732900d6b1fe467f96d67e
      Description: Deletes Objects from S3
      Handler: helper.handler_deldir
      Role:
        Fn::GetAtt:
        - S3MakePathRole
        - Arn
      Runtime: python3.6
      Timeout: 30
    Type: AWS::Serverless::Function
  S3MakePathRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - Ref: LambdaBaseRole
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - s3:DeleteObject
            - s3:ListBucket
            - s3:PutObject
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: write_s3_policy
    Type: AWS::IAM::Role
  S3PutObjectFunction:
    Properties:
      CodeUri: s3://ctnsampackages/09b4c39680fd77ed060c25bedc67c439
      Description: Puts Objects in S3
      Handler: helper.handler_mkdir
      Role:
        Fn::GetAtt:
        - S3MakePathRole
        - Arn
      Runtime: python3.6
      Timeout: 30
    Type: AWS::Serverless::Function
  UserGroupbendeskylab:
    Properties:
      GroupName: bendeskylabgroup
      Policies:
      - PolicyDocument:
          Statement:
          - Action: s3:GetBucketLocation
            Effect: Allow
            Resource: '*'
            Sid: VisualEditor0
          - Action: s3:HeadBucket
            Effect: Allow
            Resource: '*'
            Sid: VisualEditor3
          - Action: s3:ListAllMyBuckets
            Effect: Allow
            Resource: '*'
            Sid: VisualEditor1
          - Action: s3:ListBucket
            Condition:
              StringEquals:
                s3:delimiter:
                - /
                s3:prefix:
                - ''
                - bendeskylab/
                - bendeskylab/inputs
                - bendeskylab/results
                - bendeskylab/logs
                - bendeskylab/inputs/
                - bendeskylab/results/
                - bendeskylab/logs/
            Effect: Allow
            Resource:
            - arn:aws:s3:::bendeskymonitored
            Sid: ListBucket
          - Action:
            - s3:PutObject
            - s3:DeleteObject
            Effect: Allow
            Resource:
            - arn:aws:s3:::bendeskymonitored/bendeskylab/inputs/*
            Sid: Inputfolderwrite
          - Action:
            - s3:GetObject
            - s3:DeleteObject
            Effect: Allow
            Resource:
            - arn:aws:s3:::bendeskymonitored/bendeskylab/results/*
            - arn:aws:s3:::bendeskymonitored/bendeskylab/logs/*
            Sid: Outputfolderwrite
          Version: '2012-10-17'
        PolicyName: bendeskylabpolicy
    Type: AWS::IAM::Group
  bendeskylabUserNet:
    Properties:
      GroupName:
        Ref: UserGroupbendeskylab
      Users:
      - Ref: bendeskylabuser3050ferralhogs
      - Ref: bendeskylabuseraln2128
    Type: AWS::IAM::UserToGroupAddition
  bendeskylabuser3050ferralhogs:
    Properties:
      LoginProfile:
        Password: 9b77193ca6c302be
        PasswordResetRequired: 'false'
    Type: AWS::IAM::User
  bendeskylabuseraln2128:
    Properties:
      LoginProfile:
        Password: cc38019ae570fc07
        PasswordResetRequired: 'false'
    Type: AWS::IAM::User
  userkey3050ferralhogs:
    Properties:
      UserName:
        Ref: bendeskylabuser3050ferralhogs
    Type: AWS::IAM::AccessKey
  userkeyaln2128:
    Properties:
      UserName:
        Ref: bendeskylabuseraln2128
    Type: AWS::IAM::AccessKey
Transform: AWS::Serverless-2016-10-31
