language: python
python:
- 3.6
cache: pip
env:
  matrix:
  - eventfile="condition_0_0_s3_putevent.json"
  - eventfile="condition_0_1_s3_putevent.json"
  - eventfile="condition_0_2_s3_putevent.json"
  - eventfile="condition_0_3_s3_putevent.json"
  - eventfile="condition_0_4_s3_putevent.json"
  - eventfile="condition_0_5_s3_putevent.json"
  - eventfile="condition_1_0_s3_putevent.json"
  - eventfile="condition_1_1_s3_putevent.json"
  - eventfile="condition_1_2_s3_putevent.json"
  - eventfile="condition_1_3_s3_putevent.json"
  - eventfile="condition_1_4_s3_putevent.json"
  - eventfile="condition_1_5_s3_putevent.json"
  - eventfile="condition_2_0_s3_putevent.json"
  - eventfile="condition_2_1_s3_putevent.json"
  - eventfile="condition_2_2_s3_putevent.json"
  - eventfile="condition_2_3_s3_putevent.json"
  - eventfile="condition_2_4_s3_putevent.json"
  - eventfile="condition_2_5_s3_putevent.json"
  - eventfile="condition_3_0_s3_putevent.json"
  - eventfile="condition_3_1_s3_putevent.json"
  - eventfile="condition_3_2_s3_putevent.json"
  - eventfile="condition_3_3_s3_putevent.json"
  - eventfile="condition_3_4_s3_putevent.json"
  - eventfile="condition_3_5_s3_putevent.json"
  - eventfile="condition_4_0_s3_putevent.json"
  - eventfile="condition_4_1_s3_putevent.json"
  - eventfile="condition_4_2_s3_putevent.json"
  - eventfile="condition_4_3_s3_putevent.json"
  - eventfile="condition_4_4_s3_putevent.json"
  - eventfile="condition_4_5_s3_putevent.json"
  global:
  - userdirname="ciuserstack"
  - analysisdirname="cianalysisstack"
  - AWS_DEFAULT_REGION="us-east-1"
  - secure: Gl8eqEetgNhO24C2ET236OQfOHAHSnFihioJ61pzE3XQ5X0O2At3zGTQLAJPPvtreBSw0C0yxA3ECuyhqLT+gntqVyPKBUPmxh0FoODj6qE9rkRpj24tio2eKm2kAH06BCN/uYIbZbhIzBr/KnErLnQa4tlZOpPe81KmltEMhCAaO8mMHmHMn5Ud+swKCK9kQ/3PMxaG4uCTeR7MyycveBPCD2f+K6biFO/Q1xExlb0lrprGgfr1/DJyz4a9BgDeXA6LBs4gKEQ/UzO06l1Qw1RRL5zqcIlZ+oE4zruM8dGH8C+mMlLfW5UporVN5/HMLPKPHopY9tgOZAmRlSVbS8DYsS3FwE+0J21q5VFoGfhmYTLHQL03EdfMenewxjGia/yuicfRDePzmMG3IN7lGtyJ44dULLU7BWbcFYBZ2o1b4EcNmDHBJwlwOr1EwOQLuI2Vtey10UJB4wEWf5nUpefuto0Caurwo0GGCSAhajrc4VPqCcLrHS6uzbYP/I5z1RJj3vUtJsD+IowFl5Mo6zw3GL/97nJIZLFcsz8jWoxU2/j+FqzjExrBg3mG55n9zsDvhnJb1bwFEPZwuIEvHvHLXYzouxqNfrf7UvDpSetfJ0osK9M0EvRV1QysJNN19uz7breK+LKqx7U0PPbBxq0hMr+kXoGFMgALaM8nFYw=
  - secure: DkN6+GMvlS2IkChrfJZrWT/5TWoozc1KbDcGuINVi2fvU7FbfPJZno9Z0vilx+s2yxYlpecnK/amTa4TEWAu967JNLzNqGn0MwEPf+OM+SHJwfAGzgzJdM95i/QhQvzpl3HPDOgluk1+5CLIpz7dBdNxbpVtj4K3864B6LrCRMpJ135O5K3mn7PbeBiftDw0rSv4fm9eVVsIaJVdpKZYEr9rFOHVqlizdvJ4K9v4N9jrmPx6kaH/GQKfr46l0vA0IuCTvGRDv+Fpk4bsKDzgQcWzE5qrFjH8gU7vmJNDN/2K/bk/wH6VhteC9pOznbEPZ+lNYS0HfG+zgI1naLdnsKnPcacb4On959uOX8YP1K4usfECRy292mEsaRYyydQW3Tr2DyP+QGScTaIPCl3w3nMnXpARi0f0Z9Th9sCTmv2jg1L1YnvEl+zFPHhmltvCuXpVB2pGfVCgwUWmYuKGKoHSqfFczevv3BY1bLQADza95Bb2KZjcMAUbEtiqU5ip5ToXfXLEO5ilGo1BlZ+14nqnlmMrZwsjGCJ1NMc+ELTVCiMBbdtJoWUzDh98fnxEdjwAbLf79YDXDt5wgjc0XMXCkhlltIMpUQliWg7whnHP4q6g79yQORaB+lQdu4x6i6qzmSH4xGvcP/Fa+8rIesjfvb49y80tJhNWNvtah78=
  - secure: NchiLT97yCG9dRp1yfcqmOgP5FLBqGS7NwPVsnHU0TiWxLLJAzFx8Ssp4sK1KOeDQMAEsrpLg0VMeVzl0HWjjN3OcnKafshLiYk8WkA3hlDFLizB6sLeT8mTx5LYUGfFJ8HCDNSI8SF+0eAAkS+iZ6zMGn926mdDqYLPU7qcQD358C/WkwVo9j8hrJ4QB4ocX6ciiiaDfGk0D7bYc2XOFqyMmo2qjxLxwo9OPQBFliU7CPpIm5jSZP481r+3tz+H34DNlaiOqHuZ/JTbnDipdWETH8qFA2xf4K6y53o1RFb+6zmiMOLFKJfYehHN6gqAFqh4+iyB8+uqAJai4j36/E3cwCIGAbIbW08OnQz2gwa3T4aWCWDziAsaxLz+KaJgg6qsByBwgtXJkuMwcej+m4WHCpDKrFSrBiFGv0hMVlG67feW9zrB4QCLCtKhjCDjowmYrYKE8Op1HGXak67k0vDUXSAIc5TJVv3i8vBHoW4Myj7RKhcB3BRoNudTemr4lheJR/EyxrmbgfQfvIzbM020GdOrA5wr7dtgLFriAfg6gUVO/fhcrEIvCZWc943siUrhWHGnjY2Zqm+8qMmk7bjlCtLzM7wHKTEYcNNJGYq5F8GPgrAanX8LDyJq8AwpyunwhJXEFzTe0HjbOfi791QcNZ7/ZzIqUOrDW0UgwvY=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
stages:
- experiments
- test
install:
- pip install -r requirements.txt
- pip install aws-sam-cli
before_script:
- sudo apt-get install jq
script:
- bash tests/test_permastack.sh $eventfile
jobs:
- stage: experiments
  install:
  - pip install -r requirements_experiments.txt
  script:
  - bash tests/test_experiments.sh
- stage: test
  install:
  - pip install -r requirements.txt
  - pip install aws-sam-cli
  before_script:
  - sudo apt-get install jq
  script:
  - bash tests/test_permastack.sh $eventfile
