language: python
python:
- 3.6
cache: pip
env:
  matrix:
  - eventfile="condition_0_0_s3_putevent.json"
  - eventfile="condition_0_1_s3_putevent.json"
  - eventfile="condition_0_2_s3_putevent.json"
  - eventfile="condition_0_3_s3_putevent.json"
  - eventfile="condition_0_4_s3_putevent.json"
  - eventfile="condition_0_5_s3_putevent.json"
  - eventfile="condition_1_0_s3_putevent.json"
  - eventfile="condition_1_1_s3_putevent.json"
  - eventfile="condition_1_2_s3_putevent.json"
  - eventfile="condition_1_3_s3_putevent.json"
  - eventfile="condition_1_4_s3_putevent.json"
  - eventfile="condition_1_5_s3_putevent.json"
  - eventfile="condition_2_0_s3_putevent.json"
  - eventfile="condition_2_1_s3_putevent.json"
  - eventfile="condition_2_2_s3_putevent.json"
  - eventfile="condition_2_3_s3_putevent.json"
  - eventfile="condition_2_4_s3_putevent.json"
  - eventfile="condition_2_5_s3_putevent.json"
  - eventfile="condition_3_0_s3_putevent.json"
  - eventfile="condition_3_1_s3_putevent.json"
  - eventfile="condition_3_2_s3_putevent.json"
  - eventfile="condition_3_3_s3_putevent.json"
  - eventfile="condition_3_4_s3_putevent.json"
  - eventfile="condition_3_5_s3_putevent.json"
  - eventfile="condition_4_0_s3_putevent.json"
  - eventfile="condition_4_1_s3_putevent.json"
  - eventfile="condition_4_2_s3_putevent.json"
  - eventfile="condition_4_3_s3_putevent.json"
  - eventfile="condition_4_4_s3_putevent.json"
  - eventfile="condition_4_5_s3_putevent.json"
  global:
  - userdirname="ciuserstack"
  - analysisdirname="cianalysisstack"
  - AWS_DEFAULT_REGION="us-east-1"
  - secure: WIRs4LVFiwfkf30VNjhQBl1M34szhecz37wMAqu4opihFNru/d3c9V7+yKHemRi/RTAlihSqewTQ4hGHkDCVjXjTcq7auZEiJffkLHPbCMa+X2cfmYIZMQgznrDyTaTZcYFj7EPs3101nfHxMVXsL1mZnQ3TzMYZdCqd2M6AEw7LCDQkI7BIcBXK+8FI1Jgf4evIn/zUhoxC1HUYP0aMpBwZLhtvuTQWQsNrBkwctxMN6Ev+0u13IBVx5/h00sAEZPaWeFnjDJHIlW3jVg6wXcJ+w2XXHWfnKDd1yGrp9px/ocpKqFYL3zZkGZSlqV8KSLQz+VlemgOF5Yyy8CcZS9mD4KOclHzf04YzKrUnihcePgRsdnN026JUtqszPsd+wamfz/Ru1HE3qOqLDi32BB8QjAxkcoozB/EAuW6XkY8elCueOSic23YrtlKRbFI5Z+BHv5IHGrFbYAFPHhG61FzUo9xYlIq/vFhnhSMr+1XjZv2T0ASiqj9ltAFqdf1b315aUOuD4td4YxDDXsFvRUjYyQrQ1Y+twGCadKiEtPIRcwT36ADf8Rsj+oGanldGH66UfT4LiOcMXGpRGVsw7yp/KkfXAIOELjf3DXn4cMTa9KkwFHD4XrAIWLam8ygHkjkIXHa8QhufKZhIheFQu/l7lKvDRP6w8sWGV8eXv5A=
  - secure: btfFZBySWYtt8VMs2kyUlsJhyzTEzyGHYQ/XVjAKh+JRl6y7jjZ30Jsy8ZfO1cr2rLQE7f9cP9Mp1szxVWsonwmLHrj6asJdol6yLdjA3Da6KCLGCZwxVOZhOwW/ky/C1pYreOcwZtcpuF4l0dgTY6nZZq8TdPquKXXxFJdCdh7xW00wdbD7CBTa+b+dF11/WMUo3fbnN3oOB3yf4yr4pY5jNZAULed/pWObURDpTysfi5nPsBm+4f4tdRztGyUqNW9CDsKkZLhu7wLqN0iP20aFaJEACMuJ9ZHS5LcqjQHDHnrS6YsmxWCUnb5Z98gMs4gL4thUhM8AxY6mxjFv3o3RZstZUgYL6X75iYfT6Otb1zNY6eL3i6xKAjva0y12FTGK5wXq50q8fLc9vzD94+h9RMaCawZ9w3pVYqiy6oR1GjYkBBIiXzASx27IGfU+9uPr5ixwp/mBIm6yqsyOpHvu/c5MCWeAo2u+a0UmZhZs8phkQTd24Xl56Cx7MMOXLfZQp3KQwHKTxWm5q5Tr2DKISeSct/e8Ld/xuJjK1cmp4ngBPp9lFEAsNll9jHMaW9lcwEOqF5f1stg3fbDwANuu/Tz+t/kQVxQlJQsYWp7NwZLjYvZyVxTDdzHfOT3FSzU2215HFUX3WWmLxK1j6TacMjIASK9XEzZiOJm5yXU=
  - secure: Gl8eqEetgNhO24C2ET236OQfOHAHSnFihioJ61pzE3XQ5X0O2At3zGTQLAJPPvtreBSw0C0yxA3ECuyhqLT+gntqVyPKBUPmxh0FoODj6qE9rkRpj24tio2eKm2kAH06BCN/uYIbZbhIzBr/KnErLnQa4tlZOpPe81KmltEMhCAaO8mMHmHMn5Ud+swKCK9kQ/3PMxaG4uCTeR7MyycveBPCD2f+K6biFO/Q1xExlb0lrprGgfr1/DJyz4a9BgDeXA6LBs4gKEQ/UzO06l1Qw1RRL5zqcIlZ+oE4zruM8dGH8C+mMlLfW5UporVN5/HMLPKPHopY9tgOZAmRlSVbS8DYsS3FwE+0J21q5VFoGfhmYTLHQL03EdfMenewxjGia/yuicfRDePzmMG3IN7lGtyJ44dULLU7BWbcFYBZ2o1b4EcNmDHBJwlwOr1EwOQLuI2Vtey10UJB4wEWf5nUpefuto0Caurwo0GGCSAhajrc4VPqCcLrHS6uzbYP/I5z1RJj3vUtJsD+IowFl5Mo6zw3GL/97nJIZLFcsz8jWoxU2/j+FqzjExrBg3mG55n9zsDvhnJb1bwFEPZwuIEvHvHLXYzouxqNfrf7UvDpSetfJ0osK9M0EvRV1QysJNN19uz7breK+LKqx7U0PPbBxq0hMr+kXoGFMgALaM8nFYw=
  - secure: UvpSZAbiATi5At+qFTWS+mPynYYq2WXiY1kKSVlYcRRu+Sjhp1sHv6zgQzZzfgsdkIHestTJoeBMUghZxHCb4bUeB2MQmg4AvM5C58cw+4SeO+rb2qE18pGX7yOpQAY2Z1jw51e+UPvrO5iVpovN7QEqdyTSG8IlpRZOVzyMMSDk19zQSBIEeNyo7s1gAuvMHKbok0ios8QbP94H3jTCTzqY2lQPlq/0wHw6+AUcPxr20aWvjkTIwZ0/25hiYvtlsmUS2IXskOy9m+SRBjBu9HAsIIDbr7iQqaBP9l+1+MYiwuA67bI+F0iJR11GF94jnE00n9sAd3fzPJ+6akaP4yg7qY9ddJuZHKw6EJcoUk3wnloxUmVHxYzhvkpGWsLV69zar5ixWTrwnxgFEVtj+y5p36v/OOxXDVQFup+TYiMXoFAgFtasv0tCa++Gpj/A8PWqMK34kvw9YVii5jcHna0bM/p8Pkkw3sFKFYStSo/yplINfTZtG7cCE0PFNeJcGTO9AdQIZ3BYCSajKi78b7+Qr+astyemzt5MrQ7znDJ/J3Btwohe/aXMpR4gqnhas0kGDPQ85hD++HgvnTEKunMgTyv3Pz+FS1VN587rELGdsEEQ4JH+6l6o77eDPvVrqTLEUlRyI59mFE0LfC3mGsum13Rr4fK74l3tnbl6n5Q=
  - secure: XJpBB5mitvrjgz/HbsgWYYynZiuK9XUDCKHLoUvCBahqzdk7BBHmUAaZdvqpT1yCVxip+DCem2H0NLKW6PoTskznPzx5o/CkO6Z7kxUeSj/owc/Q1UIpJVr2ogpwPgWa9W7l+usi9Teptr6Nh17DxgaMLQS8avP1TJWgI2q9sIR3BKnQ1mzyNlq6gkU/osZa6KQ2wNtIOnxobQMnETxmApOvwrpR3hSLN/+Z27DngFnd+am+BmkS9bkhkkZxkFcX+ReZFXjzDR/uaD5KNnH52c+Hcfc0LsSpNcF6hY7hYwJSaVBVrB76tDF3J429Dv177Ot4FcGGJEoNo6jqacNz8YQSpq+o2/fTGXtEK5Uos8+HlP/jsKh8jNslNwjJQ/ZK/m241NA4jacfMUw3sAjsOsYuvduHBb/Ljplxn1IXU27XX7JZ8k+4IWCfNsxSzdFQy0TtGkwirtqPqiYaWbxUfLJ10Ab1DlVpXmYSD0kpaFXiQV4H+jSDyAW1rD9LpHHcw7bLpVOhuCxGnjQ9XfxLdWNvBWm+KvcA0CQABo1pCVOmlPUC+zeEuXcp2Y6Q5kMN1FOz9DBMq3ZjL7pI8LoTg9geOtzYxI0mcDzNqaimczYdbBKzg7B+Kr4CVhrvL+LBaswID4sGiJWrXy6su2vT4XNGs9EW0R37HGDXMcilWuw=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
stages:
- experiments
- test
install:
- pip install -r requirements.txt
- pip install aws-sam-cli
before_script:
- sudo apt-get install jq
script:
- bash tests/test_permastack.sh $eventfile
jobs:
- stage: experiments
  install:
  - pip install -r requirements_experiments.txt
  script:
  - bash tests/test_experiments.sh
- stage: test
  install:
  - pip install -r requirements.txt
  - pip install aws-sam-cli
  before_script:
  - sudo apt-get install jq
  script:
  - bash tests/test_permastack.sh $eventfile
