AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Base stack that generates a bucket, end-user credentials, relevant lambda functions, and relevant EC2 instances for NCAP pipelining. 

Parameters: 
  GroupName:
    Description: Name of the group to which this pipeline belongs.
    Type: 'String'

Resources:
  ProcessPCA: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      IamInstanceProfile: 'ec2-ssm'
      ImageId: 'ami-0fb68b326354c7629' 
      InstanceType: 't2.small'

  Route_Data:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: monitor_s3.handler
      Runtime: python3.6
      CodeUri: lambda_code
      Description: 'Handles event triggers from S3 and sends data to the appropriate EC2 instance. '  
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME:
            Ref: ResultsTable
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
              Resource: 'arn:aws:s3:::*'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: SourceImageBucket
            Events:
              - 's3:ObjectCreated:*'
  
  SourceImageBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref Param1

  ResultsTable:
    Type: AWS::Serverless::SimpleTable
